#!/bin/bash

cd $(dirname $0)/..
app_root=$(pwd)

thin_pidfile="$app_root/tmp/pids/thin.pid"
thin_config="$app_root/config/thin.yml"

function get_thin_pid
{
  local pid=$(cat $thin_pidfile)
  if [ -z $pid ] ; then
    echo "Could not find a PID in $thin_pidfile"
    exit 1
  fi
  thin_pid=$pid
}

function start
{
  bundle exec thin -C $thin_config -E $RAILS_ENV
}

function stop
{
  get_thin_pid
  kill -QUIT $thin_pid
}

function reload
{
  get_thin_pid
  kill -USR2 $thin_pid
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    reload
    ;;
  *)
    echo "Usage: RAILS_ENV=your_env $0 {start|stop|reload}"
    ;;
esac
